version: '3.8'

services:
  playwright-fastapi:
    container_name: playwright-fastapi
    build: .
    volumes:
      - /home/ubuntu/docker/playwright-fastapi/apps:/apps
    ports:
      - "5000:5000"
    restart: unless-stopped
