version: '3.8'

services:
  playwright-fastapi:
    container_name: playwright-fastapi
    build: .
    volumes:
      - /home/ubuntu/docker/playwright-fastapi/apps:/apps
    networks:
      - oci_mon_network
    ports:
      - "5555:5555"
 #   restart: unless-stopped
networks:
  oci_mon_network:
    external: true
